### ISSUE TITLE
How is pre-base substitution done in NotoSansMyanmar-Regular?

### ISSUE THREAD

**Issue by DavidLevinsky** [googlei18n/noto-source#106]
Hello,

I would like to know, how is pre-base substitution done in NotoSansMyanmar-Regular? This font (unlike microsoft myanmar font) does not use pre-base substitution feature 'pref', but it somehow works in text editors.  I am writing shaping engine and I spend hours by trying to figure out how is it done and how to implement that. For example where is in the font defined that sequence /pa/medial_ra will be reordered to medial_ra/pa ?

Thanks

**Comment by brawer** [comment]
Looking at the [source code for the GSUB table in Noto Sans Myanmar](https://github.com/googlei18n/noto-source/blob/master/src/NotoSansMyanmar/Noto%20Sans%20Myanmar%2026%2090%20151%20190-100%20GSUB.txt), the font indeed doesn’t use a `pres` feature.

**Comment by brawer** [comment]
Shameless plug: If you’re writing your own shaping engine, have a look at this [test suite for text rendering](https://github.com/unicode-org/text-rendering-tests). Feel free to add more test cases and/or to integrate your own engine. If your engine is proprietary, have a look at the tickets for Go and Rust (linked from the README) for how to integrate.

**Comment by behdad** [comment]
The Myanmar shaper, unlike USE, does NOT require a pref substitution to reorder the pre-base-reordering medial Ra. It just does it. Read the spec (probably useless) or check HarfBuzz source code.

You shouldn't write your own shaper by the way...

**Comment by brawer** [comment]
@DavidLevinsky, is your shaping engine for [VTS](https://melown.readthedocs.io/en/latest/index.html)? If so, consider calling [HarfBuzz](https://www.freedesktop.org/wiki/Software/HarfBuzz/) from your C++ codebase; this is what Chrome, Firefox, LibreOffice, Android and many others do. If you need browser-side shaping for some reason, have a look at [fontkit](https://github.com/devongovett/fontkit). Fontkit isn’t perfect, but it seems to work better than other JavaScript shapers. Of course you can always write your own engine, but it’s painful because the details (sadly) aren’t documented anywhere so you’d have to do a fair bit of reverse engineering.
