### ISSUE TITLE
tools to edit glyphs files

### ISSUE THREAD

**Issue by jeromew** [googlei18n/noto-source#37]
Hello,

Thanks for your work on noto. I am a newcomer to font editing. I would like to know what are my options to edit the noto .glyphs files in this repository.

It would be nice if the README could give the information.

Thank you !

**Comment by dougfelt** [comment]
https://glyphsapp.com/

**Comment by jamesgk** [comment]
For those new to font editing that don't yet want to invest in paid editing software, there's also [TruFont](https://trufont.github.io/). The issue being that TruFont works on .ufo files instead of .glyphs files, and though we have a way of converting Glyphs -> UFO, a UFO -> Glyphs converter is yet to be built.

Relevant issue: https://github.com/googlei18n/glyphsLib/issues/74
cc @adrientetar
